### ISSUE TITLE
Does not work at all with Create Fabric mod 1.20.1 v0.5.1.f

### ISSUE THREAD

**Issue by brambora69123** [TexTrueStudio/CreateFabricRecipeREICompatibility#9]
The create recipes do not show:

Example - crushing wheels
![obrazek](https://github.com/Phoupraw/CreateSDelightFabricJava/assets/74984053/2a52eed8-885e-4029-8296-4ad0a848ce67)

**Comment by FQQD** [comment]
Same problem, the mixins are failing
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Multi-argument modifier method improveStupidDisplay(Lorg/spongepowered/asm/mixin/injection/invoke/arg/Args;Lnet/minecraft/class_1860;Lme/shedaniel/rei/api/common/category/CategoryIdentifier;)V in createreibugfix.mixins.json:CreateDisplayMixin from mod createreibugfix failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap CreateFabricREIBugFix-refmap.json`

**Comment by DenisMasterHerobrine** [comment]
The same is for the `CreateFabricREIBugFix-0.1.5-create0.5.1-mc1.19.x` version. Meaning that the Create 0.5.1f update has changed it's way to support REI atleast.

The log spams with this when attempting to lookup any Create recipe
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Multi-argument modifier method improveStupidDisplay(Lorg/spongepowered/asm/mixin/injection/invoke/arg/Args;Lnet/minecraft/recipe/Recipe;Lme/shedaniel/rei/api/common/category/CategoryIdentifier;)V in createreibugfix.mixins.json:CreateDisplayMixin from mod createreibugfix failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap CreateFabricREIBugFix-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 20 more
```
